### ISSUE TITLE
Credentials remembered after Sign Out

### ISSUE THREAD

**Issue by imre** [alschmut/MSALSwiftUI#2]
# Hi @alschmut and everyone,

First of all, I really appreciate this repo, this has been a tremendous help understanding the MSAL implementation using SwiftUI.

## Context
I have implemented this solution with the relevant Azure instance, and I can successfully authenticate users (e.g., myself) using valid credentials. Everything works perfectly for signing in and using the application.

## The Problem
After signing out, I want to sign in again as a different user. However, the previously logged-in user's email address is remembered in the MSAL rendered login sheet, which appears in the browser (see screenshot).

## Desired Functionality
I would like to implement this on a shared device where users frequently sign in and out with different email addresses and credentials.

I have been searching through various docs but haven't found a viable solution for this issue using SwiftUI.

This problem only occurs on Apple devices (iOS and iPadOS). It does not happen on Android.

## Current Workaround
If you sign in through the Safari browser app to another service using the same MSAL credentials, you can sign out in the Safari browser app. This also deletes the Safari cookies for the MSAL instance, which resolves the issue temporarily, allowing the Safari Browser sheet to display a new login option.

Maybe someone knows how to wipe that cookie programatically for this app using Swift?

Any thoughts are appreciated.

## Screenshot
<img src="https://github.com/user-attachments/assets/592be55e-b22a-49d9-9c4e-b31b393eea0b" width="550" />

**Comment by alschmut** [comment]
Hi @notimre, I am glad the repository helped setting things up. I think what you might be looking for is setting the promtType of MSALInteractiveTokenParameters to a different value when interactively signing the user in. The below link gives more details :)

https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-ios

**Comment by imre** [comment]
@alschmut thank you!!! you saved me days of headache.

### This was a simple line of code, I overlooked in the docs:

```markdown
The promptType property of MSALInteractiveTokenParameters configures the authentication and consent prompt behavior. The following values are supported:

    .promptIfNecessary (default) - The user is prompted only if necessary. The SSO experience is determined by the presence of cookies in the webview, and the account type. If multiple users are signed in, account selection experience is presented. This is the default behavior.
    .selectAccount - If no user is specified, the authentication webview presents a list of currently signed-in accounts for the user to select from.
    .login - Requires the user to authenticate in the webview. Only one account may be signed-in at a time if you specify this value.
    .consent - Requires the user to consent to the current set of scopes for the request.
```

```swift
func acquireTokenInteractively() {

    guard let applicationContext = self.applicationContext else { return }
    guard let webViewParameters = self.webViewParameters else { return }

    // #1
    let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
    parameters.promptType = .selectAccount // MARK: This was the problem, as it defaults to `promptIfNecessary`

    // #2
    applicationContext.acquireToken(with: parameters) { (result, error) in

        // #3
        if let error = error {

            self.updateLogging(text: "Could not acquire token: \(error)")
            return
        }

        guard let result = result else {

            self.updateLogging(text: "Could not acquire token: No result returned")
            return
        }

        // #4
        self.accessToken = result.accessToken
        self.updateLogging(text: "Access token is \(self.accessToken)")
        self.updateCurrentAccount(account: result.account)
        self.getContentWithToken()
    }
}
```
